#! /bin/bash
# /etc/init.d/kibana

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting Kibana. This might take some time, even after the script has been finished executing."
    echo "So please be patient ..."
    nohup /srv/kibana/bin/kibana > /dev/null 2>&1 &
    ;;
  stop)
    # Quick and dirty solution, don't ever do this in reality
    echo "Stopping Kibana ..."
    pkill -f node
    ;;
  *)
    echo "Usage: /etc/init.d/kibana {start|stop}"
    exit 1
    ;;
esac

exit 0